ALTER TABLE t_p56538376_rpg_creative_platfor.stories 
ADD COLUMN IF NOT EXISTS story_context TEXT,
ADD COLUMN IF NOT EXISTS actions_log JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;